browser=chrome
url=https://www.poscentral.biz/	  
 
Login--- 
useremail=shubhamtest333@gmail.com
invalidemail=invalidemail@invalid.com
emailspace=      shubhamtest333@gmail.com
c_password=Bwit@123
w_password=Bwit@12345

Registraion---
Ruseremail=test555@gmail.com
usermobile=423456524
userfirstname=Rahul
userlastname=Kumar
useraddress=Delhi 6
usercitysuburb=new Delhi
userzipcode=4321
usercountry=Australia
userstate=Queensland

ConatctUsForm---
contactfirstname=Rahul
contactlastname=Kumar
contactcompanyname=Broadway Infotech Pvt Ltd
contactemail=rahultest123@gmail.com
contactphone=423456524
contactsubject=Test Contact Us Form
contactmessage=This is a test message for contact us form. Please ignore this message.
